---
database:
  port: 28015
  host: 127.0.0.1
  db: fanuc_robot
  user: "admin"
  passwd: ""
robots:
- name: 'E234'
  passwd: ''
  user: ''
  ip: '192.168.2.1'
  port: 21
- name: 'E2'
  passwd: ''
  user: ''
  ip: '192.168.2.2'
  port: 21